name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [ backend, frontend ]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ${{ matrix.project }}
        run: npm ci

      - name: Build frontend
        if: matrix.project == 'frontend'
        working-directory: frontend
        run: npm run build

      - name: (Placeholder) Test backend
        if: matrix.project == 'backend'
        working-directory: backend
        run: echo "No build needed for backend yet"
